name: Build

on:
  workflow_dispatch:
  
jobs:
  build-windows-release:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
        with:
          clean: true
          submodules: recursive
          fetch-depth: 0

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
      
      - name: build
        run: msbuild samp-gps-plugin.vsxproj -t:rebuild -property:Configuration=Release
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: samp-gps-win-release
          path: Release/samp-gps-plugin.dll
